### ISSUE TITLE
akkajstypedtestkit throws unexpected NoSuchElementException

### ISSUE THREAD

**Issue by Atry** [unicredit/akka.js#96]
```
git clone https://github.com/Atry/akkajstestbug.git && cd akkajstestbug && sbt test
```

```
Cloning into 'akkajstestbug'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 11 (delta 0), reused 11 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), done.
[info] Loading global plugins from /Users/twer/.sbt/1.0/plugins/project
[info] Loading settings for project global-plugins from idea.sbt,mavenResolvers.sbt,metals.sbt ...
[info] Loading global plugins from /Users/twer/.sbt/1.0/plugins
[info] Loading settings for project akkajstestbug-build from plugins.sbt ...
[info] Loading project definition from /private/tmp/akkajstestbug/project
[info] Updating ProjectRef(uri("file:/private/tmp/akkajstestbug/project/"), "akkajstestbug-build")...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project akkajstestbug from build.sbt ...
[info] Set current project to akkajstestbug (in build file:/private/tmp/akkajstestbug/)
[info] Updating ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Compiling 1 Scala source to /private/tmp/akkajstestbug/target/scala-2.12/test-classes ...
[info] Done compiling.
[info] Fast optimizing /private/tmp/akkajstestbug/target/scala-2.12/akkajstestbug-test-fastopt.js
[info] MyTest:
[info] - Unexpected NoSuchElementException *** FAILED ***
[info]   java.util.NoSuchElementException:
[info]   at java.util.NoSuchElementException.fillInStackTrace(/private/tmp/akkajstestbug/target/scala-2.12/akkajstestbug-test-fastopt.js:37821:14)
[info]   at java.util.NoSuchElementException.<init>(/private/tmp/akkajstestbug/target/scala-2.12/akkajstestbug-test-fastopt.js:37929:10)
[info]   at java.util.NoSuchElementException.<init>(/private/tmp/akkajstestbug/target/scala-2.12/akkajstestbug-test-fastopt.js:64386:58)
[info]   at akka.actor.testkit.typed.internal.LinkedBlockingDeque.removeFirst(/private/tmp/akkajstestbug/target/scala-2.12/akkajstestbug-test-fastopt.js:99010:46)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveOne$undinternal(/private/tmp/akkajstestbug/target/scala-2.12/akkajstestbug-test-fastopt.js:41769:24)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage$undinternal(/private/tmp/akkajstestbug/target/scala-2.12/akkajstestbug-test-fastopt.js:41806:16)
[info]   at {anonymous}()(/private/tmp/akkajstestbug/target/scala-2.12/akkajstestbug-test-fastopt.js:110441:49)
[info]   at scala.scalajs.runtime.AnonFunction0.apply(/private/tmp/akkajstestbug/target/scala-2.12/akkajstestbug-test-fastopt.js:50394:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(/private/tmp/akkajstestbug/target/scala-2.12/akkajstestbug-test-fastopt.js:4786:7)
[info]   at org.scalatest.Transformer.apply(/private/tmp/akkajstestbug/target/scala-2.12/akkajstestbug-test-fastopt.js:77183:10)
[info]   ...
[info] Run completed in 367 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[error] Failed tests:
[error] 	mypackage.MyTest
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 13 s, completed 2019-6-11 13:25:40
```

**Comment by andreaTP** [comment]
Hi,
thanks a lot for your bug report!
I will look better into it as soon as I'm back from Scala Days, still TestProbe in Akka Typed testkit is kinda of unsupported, and that's probably the root cause of your error.

Again, thanks a lot for the repro.

**Comment by andreaTP** [comment]
I have had a little time to take a look actually.
Here you have a fix:
https://github.com/akka-js/akka.js/commit/92741be441ca424ba74629febd1427c91b857eaa

I will integrate it in next release.

**Comment by andreaTP** [comment]
Akka JS 1.2.5.23 is on it's way to maven central and contains the fix.

Thanks again for reporting!
